// Global Types
export const OPEN_ADD_NEW_TODO_COMP = 'OPEN_ADD_NEW_TODO_COMP';
export const OPEN_EDIT_TODO_COMP = 'OPEN_EDIT_TODO_COMP';
export const TOGGLE_NOTIFICATION_MESSAGE = 'TOGGLE_NOTIFICATION_MESSAGE';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
